sudo: false
language: python
python: 
 - 2.7
 - 3.3
 - 3.4
 - 3.5
before_install:
 - git clone git@github.com:OnroerendErfgoed/crabpy.git
 - (cd crabpy && git checkout 69_deprecate_capakey_soap)
install:
 - python setup.py develop
 - pip install -r requirements-tci.txt
 - pip install nose coverage nose-testconfig coveralls webtest
script: 
  nosetests --nologcapture --config nose_cover.cfg --tc-file nose_travis.ini
after_success:
  coveralls
