sudo: false
language: python
python: 
 - 2.7
 - 3.5
install:
 - python setup.py develop
 - pip install -r requirements.txt
 - pip install nose coverage nose-testconfig coveralls webtest
script: 
  nosetests --nologcapture --config nose_cover.cfg --tc-file nose_travis.ini
after_success:
  coveralls
