dist: focal
sudo: false
language: python
python: 
 - 3.11
install:
 - pip install -r requirements-dev.txt
 - pip install -e .
script: 
  cd crabpy_pyramid; python -m unittest discover -s tests
after_success:
  coveralls
