language: python
python: 
 - "2.7"
 - "3.2"
 - "3.3"
install:
 - easy_install -U setuptools
 - python setup.py -q install
 - pip install nose coverage
 - pip install coveralls
script: 
  nosetests
after_success:
  coveralls
